variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  DOCKER_TLS_CERTDIR: '/certs'

stages:
  - analyze
  - test
  - build

linter:
  stage: analyze
  allow_failure: false
  image: node
  script:
    - npm install
    - npm run lint

formatter:
  stage: analyze
  allow_failure: false
  image: node
  script:
    - npm install
    - npm run format

test:
  stage: test
  allow_failure: false
  image: node
  script:
    - npm install
    - npm run test

build:
  stage: build
  allow_failure: false
  except:
    - tags
  image: node
  script:
    - npm install
    - npm run build

build-push-docker-image-job:
  image: docker:stable
  stage: build
  only:
    - tags
  # Specify an additional image 'docker:dind' ("Docker-in-Docker") that
  # will start up the Docker daemon when it is brought up by a runner.
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
