version: '3.7'

services:
    development:
     build:
       context: .
       dockerfile: Dockerfile
       args:
         - NPM_TOKEN=${NPM_TOKEN}
     env_file:
       - .env
     ports:
       - "8000:8000"